Repository 2i2c-org/jupyter-launcher-shortcuts, pull requests merged in 2024-07, with the labels that each got.

#24 Support jupyterlab 4 and drop jupyterlab <4 and notebook <7 support
  .gitignore
  .yarnrc.yml
  DEV.rst
  README.rst
  install.json
  jupyter_launcher_shortcuts/__init__.py
  jupyter_launcher_shortcuts/api.py
  jupyter_launcher_shortcuts/config.py
  jupyter_launcher_shortcuts/etc/serverextension.json
  jupyterlab-launcher-shortcuts/.gitignore
  jupyterlab-launcher-shortcuts/README.md
  jupyterlab-launcher-shortcuts/package.json
  jupyterlab-launcher-shortcuts/tsconfig.json
  jupyterlab-launcher-shortcuts/yarn.lock
  package.json
  pyproject.toml
  setup.py
  src/index.ts
  style/index.css
  tsconfig.json
Labels: breaking

#27 Version control yarn.lock as release automation otherwise errors
  .github/workflows/release.yaml
  .gitignore
  RELEASE.md
  yarn.lock
Labels: maintenance

#29 Add changelog for v4.0.0
  CHANGELOG.md
Labels: documentation

#30 ci: fix setting up credentials to publish a release to npm
  .github/workflows/release.yaml
Labels: ci

#31 Add changelog for v4.0.1
  CHANGELOG.md
Labels: documentation

#32 Fix labextension name (jupyterlab-launcher-shortcuts, not jupyter-)
  .github/workflows/release.yaml
  package.json
  yarn.lock
Labels: bug

#33 Add changelog for v4.0.2
  CHANGELOG.md
Labels: documentation

#34 Fix to make npm package not be empty
  .github/workflows/release.yaml
  RELEASE.md
  labextension/.yarnrc.yml
  labextension/LICENSE
  labextension/install.json
  labextension/package.json
  labextension/src/index.ts
  labextension/style/index.css
  labextension/tsconfig.json
  labextension/yarn.lock
  pyproject.toml
Labels: bug

#35 Add changelog for v4.0.3
  CHANGELOG.md
Labels: documentation

#36 Fix link formattin in README
  README.md
Labels: documentation
